version: '3.8'

services:
  sanctum:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      CLIENT_ORIGIN: http://localhost:3001
    volumes:
      - ./server/db:/app/server/db
